# Generated by Django 6.0.6 on 2026-06-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('inventory', '0002_alter_inventorytransactions_quantity_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='attending_doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='admissions_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='inventory.beds'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='admissions_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labreports',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='inventory.labtestcatalog'),
        ),
        migrations.AlterField(
            model_name='labreports',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labreports',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'LabTech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports_as_technician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='clinical.appointments'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptionitems',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='inventory.medicineinventory'),
        ),
    ]
