# Generated by Django 6.0.6 on 2026-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_admissions_attending_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitems',
            name='quantity_prescribed',
            field=models.IntegerField(default=1),
        ),
    ]
