# Generated by Django 6.0.6 on 2026-06-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_prescriptionitems_quantity_prescribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='clinical.appointments'),
        ),
        migrations.AddField(
            model_name='labreports',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='clinical.appointments'),
        ),
    ]
