# Generated by Django 6.0.6 on 2026-06-16 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charged_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.appointments')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_charges', to='billing.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='LabCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charged_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_charges', to='billing.invoices')),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.labreports')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charged_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_charges', to='billing.invoices')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.prescriptionitems')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_billed', models.IntegerField()),
                ('charged_daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.admissions')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_charges', to='billing.invoices')),
            ],
        ),
    ]
