# Generated by Django 6.0.6 on 2026-06-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinical', '0002_alter_admissions_attending_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcharges',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='clinical.appointments'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='patient_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labcharges',
            name='lab_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='clinical.labreports'),
        ),
        migrations.AlterField(
            model_name='pharmacycharges',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='clinical.prescriptionitems'),
        ),
        migrations.AlterField(
            model_name='roomcharges',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='clinical.admissions'),
        ),
    ]
