# Generated by Django 6.0.6 on 2026-06-17 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_consultationcharges_appointment_and_more'),
        ('clinical', '0002_alter_admissions_attending_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcharges',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charges', to='clinical.appointments'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='labcharges',
            name='lab_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.labreports'),
        ),
        migrations.AlterField(
            model_name='pharmacycharges',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.prescriptionitems'),
        ),
        migrations.AlterField(
            model_name='roomcharges',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.admissions'),
        ),
    ]
