# Generated by Django 6.0.6 on 2026-06-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_consultationcharges_appointment_and_more'),
        ('clinical', '0004_admissions_appointment_labreports_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='clinical.appointments'),
        ),
    ]
