# Generated by Django 6.0.6 on 2026-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactions',
            name='quantity_change',
            field=models.IntegerField(),
        ),
    ]
